---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
# esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
# resources:
#   requests:
#     cpu: "100m"
#     memory: "512M"
#   limits:
#     cpu: "1000m"
#     memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  # storageClassName: "local-path"
  resources:
    requests:
      storage: 100M


# readinessProbe:
#    failureThreshold: 3
#    initialDelaySeconds: 200
#    periodSeconds: 10
#    successThreshold: 3
#    timeoutSeconds: 5

nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: layer
        operator: NotIn
        values:
        - meta-monitoring

replicas: 1