{
 "title": "cAdvisor from Prometheus",
 "description": "cAdvisor/Prometheus-metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "min((node_filesystem_size{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} - node_filesystem_free{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal{instance=~\"$server:.*\"} - node_memory_MemAvailable{instance=~\"$server:.*\"}) / node_memory_MemTotal{instance=~\"$server:.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal{instance=~'$server:.*'} - node_memory_SwapFree{instance=~'$server:.*'})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu{instance=~\"$server:.*\"}))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server:.*\"} / count by(job, instance)(count by(job, instance, cpu)(node_cpu{instance=~\"$server:.*\"}))"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{fstype=\"aufs\"} - node_filesystem_free{fstype=\"aufs\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(node_disk_bytes_read[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_bytes_written[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "TotalAvg - CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m]) * 100",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", container=~\"ms-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m])) * 100",
     "legendFormat": "Sum MS"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m])) * 100",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "TotalAvg - Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(container_memory_working_set_bytes{namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m])",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{namespace=\"default\", container=~\"ms-.*\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum MS"
    },
    {
     "expr": "sum(avg_over_time(container_memory_working_set_bytes{namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "TotalAvg - Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[15m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",namespace=\"default\", pod!~\"loadgenerator-.*\", pod=~\"adservice.*|cartservice.*|checkoutservice.*|currencyservice.*|emailservice.*|frontend.*|paymentservice.*|productcatalogservice.*|recommendationservice.*|shippingservice.*\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum MS"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "TotalAvg - Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[15m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", pod=~\"adservice.*|cartservice.*|checkoutservice.*|currencyservice.*|emailservice.*|frontend.*|paymentservice.*|productcatalogservice.*|recommendationservice.*|shippingservice.*\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum MS"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[15m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}[5m]) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"default\", pod!~\"loadgenerator-.*\", container!=\"\", id=~\"/kubelet/.*\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!~\"\",namespace=\"default\", pod!~\"loadgenerator-.*\", id=~\"/kubelet/.*\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}