---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meta-prometheus
  labels:
    app: meta-prometheus
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics # required so that prometheus can scrape from kubelets' metrics/cadvisor
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
# - nonResourceURLs:
#   - /metrics
#   verbs:
#   - get
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch