apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   prometheus.io/scrape: 'true'
  labels:
    name: meta-prometheus
  name: meta-prometheus
  namespace: meta-monitoring
spec:
  selector:
    app: meta-prometheus
  type: LoadBalancer
  ports:
  - name: meta-prometheus
    protocol: TCP
    port: 9091
    targetPort: 9090
    # nodePort: 31091
