apiVersion: v1
kind: Service
metadata:
  name: meta-grafana
  namespace: meta-monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: meta-grafana
  sessionAffinity: None
  type: LoadBalancer