apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: meta-grafana-datasources
  namespace: meta-monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "meta-prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://meta-prometheus:9091",
                "version": 1
            }
        ]
    }